version: '3'
services:
  postgres:
    image: 'postgres:13.1'
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: blog-database
    expose:
      - '5433'
    ports:
      - '5433:5432'